version: '3.7'

services:
    client:
        build: ./client
        volumes: 
            - .:/client
        ports:
            - 8080:8080
        depends_on:
            - db
    db:
        image: mongo:3.6
        restart: always
        volumes:
            - ./db/seed.js:/seeds/seed.js
            - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    server:
        build: ./server
        volumes:
            - .:/server
        ports:
            - 3000:3000
        depends_on:
            - db
